exclude: ['CNAME', 'README.md', 'j/site.js']
include: ['.well-known']

scheme: https://
domain: bcarl.me
title: Brandon Carl

analytics:
  google: UA-8037129-7
  google_src: '/j/a.js'
  quantcast: p-7hPndKEtYPNjY
  quantcast_src: '//quantserve.com/quant.js'

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: default
