exclude: ['CNAME', 'README.md', 'img/bg-original.jpg', 'js']
include: ['.well-known']

scheme: https://
domain: bcarl.me
title: Brandon Carl

analytics:
  google: UA-8037129-7
  quantcast: p-7hPndKEtYPNjY

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: default
